# Generated by Django 5.0.6 on 2024-06-22 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0004_alter_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
    ]
